# Generated by Django 5.1.1 on 2024-10-18 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_alter_user_created_at_alter_user_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInherit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedTo',
            fields=[
                ('modelinherit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mail.modelinherit')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
            ],
            bases=('mail.modelinherit',),
        ),
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('modelinherit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mail.modelinherit')),
                ('mail_id', models.CharField(max_length=200, unique=True)),
                ('handling_officer', models.CharField(max_length=100)),
                ('dispatch_date', models.DateField(auto_now_add=True)),
                ('mail_status', models.CharField(choices=[('Drafted', 'Drafted'), ('In Transit', 'In Transit'), ('Received', 'Received')], default='Drafted', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.assignedto')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_location', to='authentication.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_location', to='authentication.location')),
            ],
            bases=('mail.modelinherit',),
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('modelinherit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mail.modelinherit')),
                ('individual_mail_id', models.CharField(max_length=100, unique=True)),
                ('mail_description', models.TextField(null=True)),
                ('priority_level', models.CharField(choices=[('Standard', 'Standard'), ('High Priority', 'High Priority')], max_length=15)),
                ('is_received', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('mail_box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_mails', to='mail.mailbox')),
            ],
            bases=('mail.modelinherit',),
        ),
    ]
