# Generated by Django 5.1.1 on 2024-11-05 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_created_at_alter_user_updated_at'),
        ('mail', '0008_alter_mail_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='recalled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='recalled_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.location'),
        ),
    ]
