# Generated by Django 5.1.1 on 2024-11-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_mail_recalled_mail_recalled_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='recalled',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='recalled_location',
        ),
    ]
