# Generated by Django 5.1.1 on 2024-11-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_recall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recall',
        ),
    ]
