# Generated by Django 5.1.1 on 2024-11-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0017_recall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recall',
        ),
    ]
